import base from "@platform/config/eslint";

export default [
  ...base,
  {
    // Generated by `next build` and explicitly marked "should not be
    // edited". Next 15.5 added a triple-slash reference to it, which the
    // shared config rejects — so linting it fails the build for a file
    // nobody wrote and nobody may fix.
    ignores: ["apps/*/next-env.d.ts"],
  },
  {
    // packages/db is the one place allowed to touch the raw client —
    // it is what implements withTenant() in the first place.
    files: ["packages/db/src/**"],
    rules: { "no-restricted-imports": "off" },
  },
];
