import { SEARCH_TEXT_CONFIG } from "@platform/db/schema";

/**
 * Storefront search.
 *
 * Postgres full-text to start (PLATFORM_BLUEPRINT.md §1 Phase 1). The
 * `products.search_vector` column is generated by the database, so the
 * index can never drift from the rows — but only if queries are parsed
 * with the SAME text search configuration the column was built with.
 * Search 'english' content with 'simple' and stemming stops matching:
 * "shirts" no longer finds "shirt", and nothing errors.
 *
 * That constant lives next to the column definition in @platform/db and
 * is imported here rather than repeated.
 */
export { SEARCH_TEXT_CONFIG };

/**
 * Longest query worth honouring. Beyond this it is a paste or an
 * attack, and tsquery parsing cost grows with term count.
 */
const MAX_QUERY_LENGTH = 128;

/**
 * Cleans a raw query string from a URL.
 *
 * Returns null for anything that should not run a search at all, so
 * callers get one obvious branch — an empty `?q=` renders the category
 * listing rather than "0 results for ''".
 */
export function normalizeSearchQuery(raw: string | null | undefined): string | null {
  if (typeof raw !== "string") return null;

  const cleaned = raw
    // Control characters would reach tsquery as garbage tokens.
    .replace(/[\u0000-\u001f\u007f]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, MAX_QUERY_LENGTH);

  return cleaned.length === 0 ? null : cleaned;
}

/**
 * Which tsquery parser to use.
 *
 * `websearch_to_tsquery` is the only one safe to hand raw user input:
 * `to_tsquery` throws a syntax error on a stray `&` or an unbalanced
 * quote — a 500 on the search page from someone typing "shirts & ties".
 * `plainto_tsquery` never throws but also ignores quoted phrases and
 * OR, so "red shirt" cannot be searched as a phrase.
 *
 * websearch handles quotes, OR and leading `-` for exclusion, matching
 * what people already expect a search box to do.
 */
export const TSQUERY_FUNCTION = "websearch_to_tsquery" as const;

/**
 * Prefix-matched query for autocomplete: "shi" should offer "shirt".
 *
 * websearch_to_tsquery cannot express a prefix, so the last token gets
 * `:*` appended and the whole thing is built as a to_tsquery expression.
 * That means the input has to be sanitised to bare word characters
 * first — this is the one place a tsquery string is assembled rather
 * than parsed, so it is also the one place a stray operator could turn
 * into a syntax error.
 */
export function toPrefixTsQuery(raw: string): string | null {
  const normalized = normalizeSearchQuery(raw);
  if (!normalized) return null;

  const terms = normalized
    // Everything that is not a letter or digit in any script is a
    // separator. tsquery operators cannot survive this.
    .split(/[^\p{L}\p{N}]+/u)
    .filter((t) => t.length > 0);

  if (terms.length === 0) return null;

  return terms.map((t, i) => (i === terms.length - 1 ? `${t}:*` : t)).join(" & ");
}

/**
 * Result ordering.
 *
 * `ts_rank_cd` over the weighted vector — title (A) outranks summary (B)
 * outranks description (C), which is set when the column is generated.
 * Cover density is the right variant here: it rewards documents where
 * the terms appear close together, which is what makes a two-word
 * product search behave the way a shopper expects.
 */
export const RANK_FUNCTION = "ts_rank_cd" as const;
