#!/usr/bin/env bash
# Generates infra/env/production.env and the matching PgBouncer
# userlist from one set of secrets, so the two can never drift.
# Refuses to overwrite an existing env file: these values include the
# database passwords the postgres volume was initialised with —
# regenerating them does NOT change the database, it just locks
# every app out. To truly start over: compose down -v, delete the
# env file, re-run this script.
set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE="env/production.env"
USERLIST="docker/pgbouncer/userlist.prod.txt"

if [ -f "$ENV_FILE" ]; then
  echo "✗ $ENV_FILE already exists. Refusing to overwrite (the postgres volume was initialised with these passwords)." >&2
  exit 1
fi

rand_hex() { openssl rand -hex 32; }

POSTGRES_PASSWORD="$(rand_hex)"
APP_DB_PASSWORD="$(rand_hex)"
MIGRATOR_DB_PASSWORD="$(rand_hex)"
OTP_PEPPER="$(rand_hex)"
SESSION_SECRET="$(rand_hex)"
INTERNAL_API_SECRET="$(rand_hex)"
TLS_ASK_SECRET="$(rand_hex)"
STORAGE_ACCESS_KEY_ID="$(openssl rand -hex 10)"
STORAGE_SECRET_ACCESS_KEY="$(rand_hex)"
CREDENTIALS_MASTER_KEY="$(openssl rand -base64 32)"

mkdir -p env

cat > "$ENV_FILE" <<EOF
# Generated by infra/scripts/gen-env.sh — do not commit.
# Field documentation lives in production.env.example.
NODE_ENV=production
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
APP_DB_PASSWORD=${APP_DB_PASSWORD}
MIGRATOR_DB_PASSWORD=${MIGRATOR_DB_PASSWORD}
DATABASE_URL_APP=postgres://app_user:${APP_DB_PASSWORD}@pgbouncer:6432/platform
DATABASE_URL_MIGRATOR=postgres://app_migrator:${MIGRATOR_DB_PASSWORD}@postgres:5432/platform
REDIS_URL=redis://redis:6379
OTP_PEPPER=${OTP_PEPPER}
SESSION_SECRET=${SESSION_SECRET}
INTERNAL_API_SECRET=${INTERNAL_API_SECRET}
TLS_ASK_SECRET=${TLS_ASK_SECRET}
STOREFRONT_INTERNAL_ORIGIN=http://storefront:3000
STORAGE_DRIVER=s3
STORAGE_ENDPOINT=http://minio:9000
STORAGE_REGION=us-east-1
STORAGE_BUCKET=media
STORAGE_ACCESS_KEY_ID=${STORAGE_ACCESS_KEY_ID}
STORAGE_SECRET_ACCESS_KEY=${STORAGE_SECRET_ACCESS_KEY}
STORAGE_FORCE_PATH_STYLE=true
MINIO_ROOT_USER=${STORAGE_ACCESS_KEY_ID}
MINIO_ROOT_PASSWORD=${STORAGE_SECRET_ACCESS_KEY}
MEDIA_PUBLIC_BASE_URL=https://media.localhost
CREDENTIALS_MASTER_KEY=${CREDENTIALS_MASTER_KEY}
CUSTOM_DOMAIN_CNAME_TARGET=domains.platform.in
CUSTOM_DOMAIN_A_RECORDS=
STOREFRONT_ROOT_DOMAIN=localhost
OTP_PROVIDER=console
EOF

cat > "$USERLIST" <<EOF
; Generated by infra/scripts/gen-env.sh — do not commit.
; Plaintext entries let PgBouncer perform SCRAM pass-through, exactly
; as the dev userlist does; the difference is these are generated
; secrets on a 0600 file, not committed dev constants.
"app_user" "${APP_DB_PASSWORD}"
"app_migrator" "${MIGRATOR_DB_PASSWORD}"
EOF

chmod 600 "$ENV_FILE" "$USERLIST"

echo "✔ Wrote $ENV_FILE and $USERLIST (mode 0600)."
